<Workspace Version="0.9.1.4062" X="-319.601044398272" Y="245.157351640098" zoom="0.671684309625861" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="9c701b8f-2cc3-4812-831f-21e995891a93" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="869.112647055676" y="318.84610183153" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
    <DSRevitNodesUI.Categories guid="f2611c0b-706d-4b9a-9896-b709219db1ef" type="DSRevitNodesUI.Categories" nickname="Categories" x="575.997956522405" y="317.761514210199" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="387:Grids" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6e4ca735-587b-4db2-9c88-02c074ea18e6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Grid.Curve" x="1285.97703350099" y="-42.5764548503237" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Grid.Curve" />
    <DSRevitNodesUI.Levels guid="5076714f-3526-4ec3-90c9-869da26255c0" type="DSRevitNodesUI.Levels" nickname="Levels" x="1457.38318025233" y="189.530260945865" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="0:Level 0" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="f64afae7-890a-4c31-878c-985b13cf5730" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="FamilyInstance.ByCurve" x="1686.52955416396" y="-41.9359013597162" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false">
      <ID value="54d2ed54-b082-43b7-97f7-67e3c8bfb3b9" />
      <Name value="FamilyInstance.ByCurve" />
      <Description value="Places a line-based family instance on a given level" />
      <Inputs>
        <Input value="curve" />
        <Input value="familyType" />
        <Input value="level" />
      </Inputs>
      <Outputs>
        <Output value="familyInstance" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <CoreNodeModels.Input.StringInput guid="3bc58c93-7fbd-4ffe-88e4-0a936004537a" type="CoreNodeModels.Input.StringInput" nickname="String" x="1859.95034603072" y="230.973025532736" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>Text</System.String>
      <System.String value="Text" />
    </CoreNodeModels.Input.StringInput>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9bca10ac-93e5-4baf-890f-7603e1014fea" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="2139.13331685144" y="268.080920055315" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a233a674-d8e7-4ee5-a5da-e9c2ed59fae8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Family.Name" x="1573.25574661021" y="320.773637147877" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.Family.Name" />
    <DSRevitNodesUI.FamilyTypes guid="564ec624-8401-4eca-a71d-fab5a1dacd26" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="1212.29630342779" y="78.1763383215464" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="1:3D Grid:250mm" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="25309bd3-eac3-4bce-9922-38a62e6f4ccd" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.Reverse" x="1473.62152168879" y="-42.9316657183592" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Reverse" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9c701b8f-2cc3-4812-831f-21e995891a93" start_index="0" end="6e4ca735-587b-4db2-9c88-02c074ea18e6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9c701b8f-2cc3-4812-831f-21e995891a93" start_index="0" end="a233a674-d8e7-4ee5-a5da-e9c2ed59fae8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f2611c0b-706d-4b9a-9896-b709219db1ef" start_index="0" end="9c701b8f-2cc3-4812-831f-21e995891a93" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6e4ca735-587b-4db2-9c88-02c074ea18e6" start_index="0" end="25309bd3-eac3-4bce-9922-38a62e6f4ccd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5076714f-3526-4ec3-90c9-869da26255c0" start_index="0" end="f64afae7-890a-4c31-878c-985b13cf5730" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f64afae7-890a-4c31-878c-985b13cf5730" start_index="0" end="9bca10ac-93e5-4baf-890f-7603e1014fea" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3bc58c93-7fbd-4ffe-88e4-0a936004537a" start_index="0" end="9bca10ac-93e5-4baf-890f-7603e1014fea" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a233a674-d8e7-4ee5-a5da-e9c2ed59fae8" start_index="0" end="9bca10ac-93e5-4baf-890f-7603e1014fea" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="564ec624-8401-4eca-a71d-fab5a1dacd26" start_index="0" end="f64afae7-890a-4c31-878c-985b13cf5730" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="25309bd3-eac3-4bce-9922-38a62e6f4ccd" start_index="0" end="f64afae7-890a-4c31-878c-985b13cf5730" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="背景預覽" eyeX="3.53090119361877" eyeY="77.8244400024414" eyeZ="46.0004653930664" lookX="-8.5309009552002" lookY="-66.8244400024414" lookZ="-54.0004653930664" upX="-0.0967834666371346" upY="0.784415662288666" upZ="-0.612637758255005" />
  </Cameras>
</Workspace>